//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.TrendingServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TrendingServiceReference.ITrendingService")]
    public interface ITrendingService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrendingService/AddNewTopicTag")]
        void AddNewTopicTag(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrendingService/GetTrendingTopics", ReplyAction="http://tempuri.org/ITrendingService/GetTrendingTopicsResponse")]
        DAO.DAO.TrendingTopics[] GetTrendingTopics(string maxTag);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrendingServiceChannel : Test.TrendingServiceReference.ITrendingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrendingServiceClient : System.ServiceModel.ClientBase<Test.TrendingServiceReference.ITrendingService>, Test.TrendingServiceReference.ITrendingService {
        
        public TrendingServiceClient() {
        }
        
        public TrendingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrendingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrendingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrendingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddNewTopicTag(string message) {
            base.Channel.AddNewTopicTag(message);
        }
        
        public DAO.DAO.TrendingTopics[] GetTrendingTopics(string maxTag) {
            return base.Channel.GetTrendingTopics(maxTag);
        }
    }
}
