SET SQL_SAFE_UPDATES=0;
Delete From CountryCode;
ALTER TABLE CountryCode AUTO_INCREMENT = 1;
INSERT INTO CountryCode (code) VALUES ('Afghanistan');
INSERT INTO CountryCode (code) VALUES ('Albania');
INSERT INTO CountryCode (code) VALUES ('Algeria');
INSERT INTO CountryCode (code) VALUES ('Andorra');
INSERT INTO CountryCode (code) VALUES ('Angola');
INSERT INTO CountryCode (code) VALUES ('Antigua and Barbuda');
INSERT INTO CountryCode (code) VALUES ('Argentina');
INSERT INTO CountryCode (code) VALUES ('Armenia');
INSERT INTO CountryCode (code) VALUES ('Australia');
INSERT INTO CountryCode (code) VALUES ('Austria');
INSERT INTO CountryCode (code) VALUES ('Azerbaijan');
INSERT INTO CountryCode (code) VALUES ('Bahamas, The');
INSERT INTO CountryCode (code) VALUES ('Bahrain');
INSERT INTO CountryCode (code) VALUES ('Bangladesh');
INSERT INTO CountryCode (code) VALUES ('Barbados');
INSERT INTO CountryCode (code) VALUES ('Belarus');
INSERT INTO CountryCode (code) VALUES ('Belgium');
INSERT INTO CountryCode (code) VALUES ('Belize');
INSERT INTO CountryCode (code) VALUES ('Benin');
INSERT INTO CountryCode (code) VALUES ('Bhutan');
INSERT INTO CountryCode (code) VALUES ('Bolivia');
INSERT INTO CountryCode (code) VALUES ('Bosnia and Herzegovina');
INSERT INTO CountryCode (code) VALUES ('Botswana');
INSERT INTO CountryCode (code) VALUES ('Brazil');
INSERT INTO CountryCode (code) VALUES ('Brunei ');
INSERT INTO CountryCode (code) VALUES ('Bulgaria');
INSERT INTO CountryCode (code) VALUES ('Burkina Faso');
INSERT INTO CountryCode (code) VALUES ('Burma');
INSERT INTO CountryCode (code) VALUES ('Burundi');
INSERT INTO CountryCode (code) VALUES ('Cambodia');
INSERT INTO CountryCode (code) VALUES ('Cameroon');
INSERT INTO CountryCode (code) VALUES ('Canada');
INSERT INTO CountryCode (code) VALUES ('Cape Verde');
INSERT INTO CountryCode (code) VALUES ('Central African Republic');
INSERT INTO CountryCode (code) VALUES ('Chad');
INSERT INTO CountryCode (code) VALUES ('Chile');
INSERT INTO CountryCode (code) VALUES ('China');
INSERT INTO CountryCode (code) VALUES ('Colombia');
INSERT INTO CountryCode (code) VALUES ('Comoros ');
INSERT INTO CountryCode (code) VALUES ('Congo, Democratic Republic of the');
INSERT INTO CountryCode (code) VALUES ('Congo, Republic of the');
INSERT INTO CountryCode (code) VALUES ('Costa Rica');
INSERT INTO CountryCode (code) VALUES ('Cote d Ivoire');
INSERT INTO CountryCode (code) VALUES ('Croatia');
INSERT INTO CountryCode (code) VALUES ('Cuba');
INSERT INTO CountryCode (code) VALUES ('Cyprus');
INSERT INTO CountryCode (code) VALUES ('Czech Republic');
INSERT INTO CountryCode (code) VALUES ('Denmark');
INSERT INTO CountryCode (code) VALUES ('Djibouti');
INSERT INTO CountryCode (code) VALUES ('Dominica');
INSERT INTO CountryCode (code) VALUES ('Dominican Republic');
INSERT INTO CountryCode (code) VALUES ('East Timor (see Timor-Leste)');
INSERT INTO CountryCode (code) VALUES ('Ecuador');
INSERT INTO CountryCode (code) VALUES ('Egypt');
INSERT INTO CountryCode (code) VALUES ('El Salvador');
INSERT INTO CountryCode (code) VALUES ('Equatorial Guinea');
INSERT INTO CountryCode (code) VALUES ('Eritrea');
INSERT INTO CountryCode (code) VALUES ('Estonia');
INSERT INTO CountryCode (code) VALUES ('Ethiopia');
INSERT INTO CountryCode (code) VALUES ('Fiji');
INSERT INTO CountryCode (code) VALUES ('Finland');
INSERT INTO CountryCode (code) VALUES ('France');
INSERT INTO CountryCode (code) VALUES ('Gabon');
INSERT INTO CountryCode (code) VALUES ('Gambia, The');
INSERT INTO CountryCode (code) VALUES ('Georgia');
INSERT INTO CountryCode (code) VALUES ('Germany');
INSERT INTO CountryCode (code) VALUES ('Ghana');
INSERT INTO CountryCode (code) VALUES ('Greece');
INSERT INTO CountryCode (code) VALUES ('Grenada');
INSERT INTO CountryCode (code) VALUES ('Guatemala');
INSERT INTO CountryCode (code) VALUES ('Guinea');
INSERT INTO CountryCode (code) VALUES ('Guinea-Bissau');
INSERT INTO CountryCode (code) VALUES ('Guyana');
INSERT INTO CountryCode (code) VALUES ('Haiti');
INSERT INTO CountryCode (code) VALUES ('Holy See');
INSERT INTO CountryCode (code) VALUES ('Honduras');
INSERT INTO CountryCode (code) VALUES ('Hong Kong');
INSERT INTO CountryCode (code) VALUES ('Hungary');
INSERT INTO CountryCode (code) VALUES ('Iceland');
INSERT INTO CountryCode (code) VALUES ('India');
INSERT INTO CountryCode (code) VALUES ('Indonesia');
INSERT INTO CountryCode (code) VALUES ('Iran');
INSERT INTO CountryCode (code) VALUES ('Iraq');
INSERT INTO CountryCode (code) VALUES ('Ireland');
INSERT INTO CountryCode (code) VALUES ('Israel');
INSERT INTO CountryCode (code) VALUES ('Italy');
INSERT INTO CountryCode (code) VALUES ('Jamaica');
INSERT INTO CountryCode (code) VALUES ('Japan');
INSERT INTO CountryCode (code) VALUES ('Jordan');
INSERT INTO CountryCode (code) VALUES ('Kazakhstan');
INSERT INTO CountryCode (code) VALUES ('Kenya');
INSERT INTO CountryCode (code) VALUES ('Kiribati');
INSERT INTO CountryCode (code) VALUES ('Korea, North');
INSERT INTO CountryCode (code) VALUES ('Korea, South');
INSERT INTO CountryCode (code) VALUES ('Kosovo');
INSERT INTO CountryCode (code) VALUES ('Kuwait');
INSERT INTO CountryCode (code) VALUES ('Kyrgyzstan');
INSERT INTO CountryCode (code) VALUES ('Laos');
INSERT INTO CountryCode (code) VALUES ('Latvia');
INSERT INTO CountryCode (code) VALUES ('Lebanon');
INSERT INTO CountryCode (code) VALUES ('Lesotho');
INSERT INTO CountryCode (code) VALUES ('Liberia');
INSERT INTO CountryCode (code) VALUES ('Libya');
INSERT INTO CountryCode (code) VALUES ('Liechtenstein');
INSERT INTO CountryCode (code) VALUES ('Lithuania');
INSERT INTO CountryCode (code) VALUES ('Luxembourg');
INSERT INTO CountryCode (code) VALUES ('Macau');
INSERT INTO CountryCode (code) VALUES ('Macedonia');
INSERT INTO CountryCode (code) VALUES ('Madagascar');
INSERT INTO CountryCode (code) VALUES ('Malawi');
INSERT INTO CountryCode (code) VALUES ('Malaysia');
INSERT INTO CountryCode (code) VALUES ('Maldives');
INSERT INTO CountryCode (code) VALUES ('Mali');
INSERT INTO CountryCode (code) VALUES ('Malta');
INSERT INTO CountryCode (code) VALUES ('Marshall Islands');
INSERT INTO CountryCode (code) VALUES ('Mauritania');
INSERT INTO CountryCode (code) VALUES ('Mauritius');
INSERT INTO CountryCode (code) VALUES ('Mexico');
INSERT INTO CountryCode (code) VALUES ('Micronesia');
INSERT INTO CountryCode (code) VALUES ('Moldova');
INSERT INTO CountryCode (code) VALUES ('Monaco');
INSERT INTO CountryCode (code) VALUES ('Mongolia');
INSERT INTO CountryCode (code) VALUES ('Montenegro');
INSERT INTO CountryCode (code) VALUES ('Morocco');
INSERT INTO CountryCode (code) VALUES ('Mozambique');
INSERT INTO CountryCode (code) VALUES ('Namibia');
INSERT INTO CountryCode (code) VALUES ('Nauru');
INSERT INTO CountryCode (code) VALUES ('Nepal');
INSERT INTO CountryCode (code) VALUES ('Netherlands');
INSERT INTO CountryCode (code) VALUES ('Netherlands Antilles');
INSERT INTO CountryCode (code) VALUES ('New Zealand');
INSERT INTO CountryCode (code) VALUES ('Nicaragua');
INSERT INTO CountryCode (code) VALUES ('Niger');
INSERT INTO CountryCode (code) VALUES ('Nigeria');
INSERT INTO CountryCode (code) VALUES ('North Korea');
INSERT INTO CountryCode (code) VALUES ('Norway');
INSERT INTO CountryCode (code) VALUES ('Oman');
INSERT INTO CountryCode (code) VALUES ('Pakistan');
INSERT INTO CountryCode (code) VALUES ('Palau');
INSERT INTO CountryCode (code) VALUES ('Palestinian Territories');
INSERT INTO CountryCode (code) VALUES ('Panama');
INSERT INTO CountryCode (code) VALUES ('Papua New Guinea');
INSERT INTO CountryCode (code) VALUES ('Paraguay');
INSERT INTO CountryCode (code) VALUES ('Peru');
INSERT INTO CountryCode (code) VALUES ('Philippines');
INSERT INTO CountryCode (code) VALUES ('Poland');
INSERT INTO CountryCode (code) VALUES ('Portugal');
INSERT INTO CountryCode (code) VALUES ('Qatar');
INSERT INTO CountryCode (code) VALUES ('Romania');
INSERT INTO CountryCode (code) VALUES ('Russia');
INSERT INTO CountryCode (code) VALUES ('Rwanda');
INSERT INTO CountryCode (code) VALUES ('Saint Kitts and Nevis');
INSERT INTO CountryCode (code) VALUES ('Saint Lucia');
INSERT INTO CountryCode (code) VALUES ('Saint Vincent and the Grenadines');
INSERT INTO CountryCode (code) VALUES ('Samoa');
INSERT INTO CountryCode (code) VALUES ('San Marino');
INSERT INTO CountryCode (code) VALUES ('Sao Tome and Principe');
INSERT INTO CountryCode (code) VALUES ('Saudi Arabia');
INSERT INTO CountryCode (code) VALUES ('Senegal');
INSERT INTO CountryCode (code) VALUES ('Serbia');
INSERT INTO CountryCode (code) VALUES ('Seychelles');
INSERT INTO CountryCode (code) VALUES ('Sierra Leone');
INSERT INTO CountryCode (code) VALUES ('Singapore');
INSERT INTO CountryCode (code) VALUES ('Slovakia');
INSERT INTO CountryCode (code) VALUES ('Slovenia');
INSERT INTO CountryCode (code) VALUES ('Solomon Islands');
INSERT INTO CountryCode (code) VALUES ('Somalia');
INSERT INTO CountryCode (code) VALUES ('South Africa');
INSERT INTO CountryCode (code) VALUES ('South Korea');
INSERT INTO CountryCode (code) VALUES ('South Sudan');
INSERT INTO CountryCode (code) VALUES ('Spain');
INSERT INTO CountryCode (code) VALUES ('Sri Lanka');
INSERT INTO CountryCode (code) VALUES ('Sudan');
INSERT INTO CountryCode (code) VALUES ('Suriname');
INSERT INTO CountryCode (code) VALUES ('Swaziland');
INSERT INTO CountryCode (code) VALUES ('Sweden');
INSERT INTO CountryCode (code) VALUES ('Switzerland');
INSERT INTO CountryCode (code) VALUES ('Syria');
INSERT INTO CountryCode (code) VALUES ('Taiwan');
INSERT INTO CountryCode (code) VALUES ('Tajikistan');
INSERT INTO CountryCode (code) VALUES ('Tanzania');
INSERT INTO CountryCode (code) VALUES ('Thailand');
INSERT INTO CountryCode (code) VALUES ('Timor-Leste');
INSERT INTO CountryCode (code) VALUES ('Togo');
INSERT INTO CountryCode (code) VALUES ('Tonga');
INSERT INTO CountryCode (code) VALUES ('Trinidad and Tobago');
INSERT INTO CountryCode (code) VALUES ('Tunisia');
INSERT INTO CountryCode (code) VALUES ('Turkey');
INSERT INTO CountryCode (code) VALUES ('Turkmenistan');
INSERT INTO CountryCode (code) VALUES ('Tuvalu');
INSERT INTO CountryCode (code) VALUES ('Uganda');
INSERT INTO CountryCode (code) VALUES ('Ukraine');
INSERT INTO CountryCode (code) VALUES ('United Arab Emirates');
INSERT INTO CountryCode (code) VALUES ('United Kingdom');
INSERT INTO CountryCode (code) VALUES ('Uruguay');
INSERT INTO CountryCode (code) VALUES ('Uzbekistan');
INSERT INTO CountryCode (code) VALUES ('Vanuatu');
INSERT INTO CountryCode (code) VALUES ('Venezuela');
INSERT INTO CountryCode (code) VALUES ('Vietnam');
INSERT INTO CountryCode (code) VALUES ('Yemen');
INSERT INTO CountryCode (code) VALUES ('Zambia');
INSERT INTO CountryCode (code) VALUES ('Zimbabwe');







