#!/bin/bash
mysql -h UbuntuServer1 -u root -psqlapps planetgeni < /home/planetx/DbScripts/StoredProcedure/StoredProcedure.sql
mysql -h UbuntuServer1 -u root -psqlapps planetgeni < /home/planetx/DbScripts/StoredProcedure/CURDStoredProcedure.sql
