use planetgeni;
SET foreign_key_checks = 0;
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\AllowedWebUser.csv' INTO TABLE AllowedWebUser FIELDS TERMINATED BY ',';
UPDATE AllowedWebUser SET EmailId = REPLACE(REPLACE(EmailId, '\r', ''), '\n', '');
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\country_list.csv' INTO TABLE CountryCode FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\DegreeCode.csv' INTO TABLE DegreeCode FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\CapitalType.csv' INTO TABLE CapitalType FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\MajorCode.csv' INTO TABLE MajorCode FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\AdsType.csv' INTO TABLE AdsType FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\AdsFrequencyType.csv' INTO TABLE AdsFrequencyType FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\BudgetCode.csv' INTO TABLE BudgetCode FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\WeaponType.csv' INTO TABLE WeaponType FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\JobCode.csv' INTO TABLE JobCode FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\CountryBudgetByType.csv' INTO TABLE CountryBudgetByType FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\UserVoteChoice.csv' INTO TABLE UserVoteChoice FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\TaskType.csv' INTO TABLE TaskType FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\CountryBudget.csv' INTO TABLE CountryBudget FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\ElectionPosition.csv' INTO TABLE ElectionPosition FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\CreditInterest.csv' INTO TABLE CreditInterest FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\CreditScore.csv' INTO TABLE CreditScore FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\CountryTax.csv' INTO TABLE CountryTax FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\TaxCode.csv' INTO TABLE TaxCode FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\CountryTaxByType.csv' INTO TABLE CountryTaxByType FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\MerchandiseType.csv' INTO TABLE MerchandiseType FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\BootStrap\\Data\\UserBankAccount.csv' INTO TABLE UserBankAccount FIELDS TERMINATED BY ',' SET CreatedAT = UTC_TIMESTAMP(), UpdatedAT = UTC_TIMESTAMP();
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\BootStrap\\Data\\StockTrade.csv' INTO TABLE StockTrade FIELDS TERMINATED BY ',' SET UpdatedAT = UTC_TIMESTAMP();
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\BootStrap\\Data\\UserStock.csv' INTO TABLE UserStock FIELDS TERMINATED BY ',' SET PurchasedAT = UTC_TIMESTAMP();
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\Stock.csv' INTO TABLE Stock FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\NotificationType.csv' INTO TABLE NotificationType FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\IndustryCode.csv' INTO TABLE IndustryCode FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\JobCountry.csv' INTO TABLE JobCountry FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\JobCode.csv' INTO TABLE JobCode FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\ElectionAgenda.csv' INTO TABLE ElectionAgenda FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\FundTypeCode.csv' INTO TABLE FundTypeCode FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\ContactSource.csv' INTO TABLE ContactSource FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\ContactProvider.csv' INTO TABLE ContactProvider FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\PostContentType.csv' INTO TABLE PostContentType FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\WebJob.csv' INTO TABLE WebJob FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\NextLotteryDrawing.csv' INTO TABLE NextLotteryDrawing FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'C:\\Home\\CodeBack\\PlanetGeni\\DAL\\DbScripts\\Data\\SlotMachineThree.csv' INTO TABLE SlotMachineThree FIELDS TERMINATED BY ',';
DELETE FROM `planetgeniidentity`.AspNetUsers;
SET SQL_SAFE_UPDATES=1;
SET foreign_key_checks = 1;
