SET SQL_SAFE_UPDATES =0;
Delete From WebUser;
Delete From UserNotification;
Delete From TaskReminder;
Delete From Post;
Delete From UserBankAccount;
Delete From CapitalTransactionLog;
Delete From UserLoan;
Delete From UserStock;
Delete From Friend;
Delete From PartyMember;
Delete From PoliticalParty;
Delete From UserJob;
Delete From MajorCode;
Delete From DegreeCode;
Delete From JobCode;
Delete From IndustryCode;
Delete From WeaponType;
Delete From UserMerchandise;
Delete From Education;
Delete From BudgetCode;
Delete From CountryBudget;
Delete From CountryBudgetByType;
Delete From CountryRevenue;
Delete From CountryWeapon;
Delete From CountryLeader;
Delete From ElectionPosition;


LOAD DATA LOCAL INFILE '{0}UserBankAccount.tsv' INTO TABLE UserBankAccount FIELDS TERMINATED BY '\t' IGNORE 1 LINES;
 LOAD DATA LOCAL INFILE '{0}WebUser.tsv' INTO TABLE WebUser FIELDS TERMINATED BY '\t' IGNORE 1 LINES;
 LOAD DATA LOCAL INFILE '{0}UserMerchandise.tsv' INTO TABLE UserMerchandise FIELDS TERMINATED BY '\t' ;
 LOAD DATA LOCAL INFILE '{0}UserLoan.tsv' INTO TABLE UserLoan FIELDS TERMINATED BY '\t' ;
 LOAD DATA LOCAL INFILE '{0}UserStock.tsv' INTO TABLE UserStock FIELDS TERMINATED BY '\t' ;
 LOAD DATA LOCAL INFILE '{0}Friend.tsv' INTO TABLE Friend FIELDS TERMINATED BY '\t' ;
 LOAD DATA LOCAL INFILE '{0}PartyMember.tsv' INTO TABLE PartyMember FIELDS TERMINATED BY '\t' ;
 LOAD DATA LOCAL INFILE '{0}PoliticalParty.tsv' INTO TABLE PoliticalParty FIELDS TERMINATED BY '\t' ;
 LOAD DATA LOCAL INFILE '{0}UserJob.tsv' INTO TABLE UserJob FIELDS TERMINATED BY '\t' ;
 LOAD DATA LOCAL INFILE '{2}MajorCode.csv' INTO TABLE MajorCode FIELDS TERMINATED BY ',' ;
 LOAD DATA LOCAL INFILE '{2}DegreeCode.csv' INTO TABLE DegreeCode FIELDS TERMINATED BY ',' ;
 LOAD DATA LOCAL INFILE '{2}JobCode.csv' INTO TABLE JobCode FIELDS TERMINATED BY ',' ;
 LOAD DATA LOCAL INFILE '{2}IndustryCode.csv' INTO TABLE IndustryCode FIELDS TERMINATED BY ',' ;
 LOAD DATA LOCAL INFILE '{2}WeaponType.csv' INTO TABLE WeaponType FIELDS TERMINATED BY ',' ;
 LOAD DATA LOCAL INFILE '{2}BudgetCode.csv' INTO TABLE BudgetCode FIELDS TERMINATED BY ',' ;
 LOAD DATA LOCAL INFILE '{2}ElectionPosition.csv' INTO TABLE ElectionPosition FIELDS TERMINATED BY ',' ;
 LOAD DATA LOCAL INFILE '{0}UserMerchandise.tsv' INTO TABLE UserMerchandise FIELDS TERMINATED BY '\t'  ;
 LOAD DATA LOCAL INFILE '{0}Education.tsv' INTO TABLE Education FIELDS TERMINATED BY '\t'  ;
 LOAD DATA LOCAL INFILE '{0}CountryBudget.tsv' INTO TABLE CountryBudget FIELDS TERMINATED BY '\t'  ;
 LOAD DATA LOCAL INFILE '{0}CountryBudgetByType.tsv' INTO TABLE CountryBudgetByType FIELDS TERMINATED BY '\t'  ;
 LOAD DATA LOCAL INFILE '{0}CountryRevenue.tsv' INTO TABLE CountryRevenue FIELDS TERMINATED BY '\t'  ;
 LOAD DATA LOCAL INFILE '{0}CountryWeapon.tsv' INTO TABLE CountryWeapon FIELDS TERMINATED BY '\t'  ;
 LOAD DATA LOCAL INFILE '{0}CountryLeader.tsv' INTO TABLE CountryLeader FIELDS TERMINATED BY '\t'  ;
 