//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RulesEngine.ReminderServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReminderServiceReference.IReminderService")]
    public interface IReminderService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IReminderService/RunTaskReminder")]
        void RunTaskReminder();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IReminderService/RunTaskReminder")]
        System.Threading.Tasks.Task RunTaskReminderAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IReminderService/RunTaskReminderByType")]
        void RunTaskReminderByType(int taskType);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IReminderService/RunTaskReminderByType")]
        System.Threading.Tasks.Task RunTaskReminderByTypeAsync(int taskType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReminderServiceChannel : RulesEngine.ReminderServiceReference.IReminderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReminderServiceClient : System.ServiceModel.ClientBase<RulesEngine.ReminderServiceReference.IReminderService>, RulesEngine.ReminderServiceReference.IReminderService {
        
        public ReminderServiceClient() {
        }
        
        public ReminderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReminderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReminderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReminderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RunTaskReminder() {
            base.Channel.RunTaskReminder();
        }
        
        public System.Threading.Tasks.Task RunTaskReminderAsync() {
            return base.Channel.RunTaskReminderAsync();
        }
        
        public void RunTaskReminderByType(int taskType) {
            base.Channel.RunTaskReminderByType(taskType);
        }
        
        public System.Threading.Tasks.Task RunTaskReminderByTypeAsync(int taskType) {
            return base.Channel.RunTaskReminderByTypeAsync(taskType);
        }
    }
}
